<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.10">
  <POU Name="pPLC_Diagnostics" Id="{102759fd-9553-4b1c-afe0-5109c46f73f2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM pPLC_Diagnostics
VAR
	//FB
	fbCheckLicense	:	FB_CheckLicense;
	fbGetSystemId	:	FB_GetSystemId;
	//Variables
	xGetSystemId: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="pPLC_Diagnostics">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>