<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ResetCircuitBreakerGlobals" Id="{af07064f-81b8-4e8e-bacc-84cfa4b1f877}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION ResetCircuitBreakerGlobals : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[GVL_Logger.bTrickleTripped := FALSE;
GVL_Logger.nGlobAccEvents := 0;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>