<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="RUN_TESTS" Id="{e6fc24fd-e279-490c-8a71-fd69372c3aaa}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM RUN_TESTS
VAR
    CbTest    :    FB_CircuitBreaker_Test;
    fbCentroidTest : FB_Test_EpicsCentroidMonitor;
    fbMotorTest : FB_Test_EpicsMotorMonitor;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>